### ISSUE TITLE
add option to show both tabs per window count, and global tab count

### ISSUE THREAD

**Issue by insaner** [asafh/chrome-tabcounter#3]
Currently I have to click to toggle which type of tab count to show.. it would be great if you could add the option to just show both at the same time. Thanks for the great, simple tab counter!

**Comment by asafh** [comment]
@insaner Sure, I've added a third mode which displays them both (e.g. "21/4"), I've published it to the chrome store but it might take a few hours to show.
Code is available in tag [v1.1](https://github.com/asafh/chrome-tabcounter/tree/v1.1)

**Comment by insaner** [comment]
Awesome! Thanks! I will check again tomorrow (still not up yet).

**Comment by insaner** [comment]
Hi I can confirm that it has been updated on the chrome store, but at least for me (having not restarted chrome yet) it shows only "total tabs"/"2" (ie, the second number is always "2"). Also, would it be possible to have the number of tabs in the given window be the leftmost number? "tabs in this window/total tabs"

Thanks again!

**Comment by asafh** [comment]
I assume that even if you open new opens the number stays two?  If this persisted after restart, could you a. send me a screen shot if possible b. Can you see under the extension page chrome://extensions the extension would have a 'Inspect views: Background page' - anything printed in the log?

Per-window stats has two issues:
1. Choosing this many options would need a better system then alternate clicking, but this just means some work for me.  
2. Unfortunately the way chrome extension's browserAction works (which is the button or the extension), it is the same button across all windows/tabs - i.e. you can't have different badge for each window. While you could change the text based on what window is in focus, this can give confusing information at times.

**Comment by asafh** [comment]
To refine the constraint in point number 2, you could have the badge text differ per tab but then we'll need to do some book keeping about what tab is in which window.

**Comment by insaner** [comment]
Hi, just restarted the browser, and can confirm it remains at [# tabs total]/2
Nothing in the inspect views log. Let me know what other info to provide that could be of help.

**Comment by asafh** [comment]
@insaner Sorry this somewhat slipped my mind. Could you tell me what version of Chrome are you using?
It is odd for the number of windows displayed to be fixed to 2 even when adding/closing windows.  
If we won't be able to identify the issue I can publish a second version with some debugging prints, then we could perhaps get a hint at what goes wrong.

**Comment by insaner** [comment]
48.0.2564.82
Right now the three displays are: "360", "30", "360/3" and that's on all windows, regardless of how many tabs are on that window. The total windows does update correctly if I open new tabs ("360" -> "361").

**Comment by asafh** [comment]
Slightly confused - you mean the total tabs updates correctly?  
Just to explicitly say the defined behaviour is for the text to show "<sum of number of tabs in all windows> / <number of windows>". That is, the same text appears in all windows/tabs. Is this what you experience and you expect something else, or are you experiencing something else?

**Comment by asafh** [comment]
PS -your chrome version dated ~2015? Updates are disabled? Worth updating it.

**Comment by insaner** [comment]
Yeah, it is a pretty old version, I will update soon. The extension updated automatically though. So, to clarify, if I open a new tab the three displays go from "360", "360/3", "30" to "361", "361/3", "30". This is on a window with 9 tabs. Same behavior on all windows as far as I know. Ie, the per window count is not being updated correctly. It did with the previous version of the extension if I remember correctly

**Comment by asafh** [comment]
Actually there was never functionally to display a tab number per window, which is I think the gap between what you're experiencing and expecting. All displays will always show the same text.

**Comment by insaner** [comment]
Ok, through a bit of testing I figured out what is going on with the display that I wasn't understanding. The displays as mentioned: "360", "360/3", "30" are indeed for the total number of tabs across all windows and number of windows, with  "360/3" meaning "360 tabs total, and 30 windows". This of course means there is a display bug that shows only the first digit of the total number of windows as "3" instead of "30".

It would be great if you could eventually implement the feature of showing the number of tabs per window next to the number of total tabs, as that is the feature I most wish this extension would have.

**Comment by insaner** [comment]
I read in other Chrome addons that using the "badge" display only allows 4 characters to be displayed max. This would be consistent with the problem I am having where only the first character of the window count is displayed. Just in case it was useful information for you.
